server:
  port: 8087
spring:
  application:
    name: auth-service
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
ly:
  jwt:
    pubKeyPath: E://11//upload//rsa.pub
    priKeyPath: E://11//upload//rsa.pri
    expire: 30
    cookieName: LY_TOKEN