server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.58.128
    username: leyou
    password: leyou
    virtual-host: /leyou
ly:
  sms:
    accessKeyId: LTAIf5vJTEe7OiPa
    accessKeySecret: A2ZGBWfrkz9arF9O8cmDWXmIrAlngA
    connectTimeout: 5000
    readTimeout: 8000
    signName: 乐优商城
    verifyTemplateCode: SMS_133976814
